"""add webhook contract validation

Revision ID: dfb81f1b6717
Revises: 88c9fdc5dac0
Create Date: 2026-07-16 15:21:55.022936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb81f1b6717'
down_revision: Union[str, Sequence[str], None] = '88c9fdc5dac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('contract_valid', sa.Boolean(), nullable=True))
    op.add_column('deliveries', sa.Column('contract_issues', sa.JSON(), nullable=True))
    op.add_column('webhook_endpoints', sa.Column('contract_baseline', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_endpoints', 'contract_baseline')
    op.drop_column('deliveries', 'contract_issues')
    op.drop_column('deliveries', 'contract_valid')
    # ### end Alembic commands ###
