"""add duplicate detection fields

Revision ID: 6be3755c2da8
Revises: dfb81f1b6717
Create Date: 2026-07-16 18:02:34.203161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be3755c2da8'
down_revision: Union[str, Sequence[str], None] = 'dfb81f1b6717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('payload_fingerprint', sa.String(length=64), nullable=True))
    op.add_column('deliveries', sa.Column('duplicate_of_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_deliveries_payload_fingerprint'), 'deliveries', ['payload_fingerprint'], unique=False)
    op.create_foreign_key(None, 'deliveries', 'deliveries', ['duplicate_of_id'], ['id'])
    op.add_column('webhook_endpoints', sa.Column('duplicate_detection_enabled', sa.Boolean(), nullable=False, server_default=sa.false(),))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_endpoints', 'duplicate_detection_enabled')
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.drop_index(op.f('ix_deliveries_payload_fingerprint'), table_name='deliveries')
    op.drop_column('deliveries', 'duplicate_of_id')
    op.drop_column('deliveries', 'payload_fingerprint')
    # ### end Alembic commands ###
