"""add next retry time

Revision ID: 88c9fdc5dac0
Revises: 102877607833
Create Date: 2026-07-15 20:33:17.518139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c9fdc5dac0'
down_revision: Union[str, Sequence[str], None] = '102877607833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_deliveries_next_retry_at'), 'deliveries', ['next_retry_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliveries_next_retry_at'), table_name='deliveries')
    op.drop_column('deliveries', 'next_retry_at')
    # ### end Alembic commands ###
